name: Android CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug APK with Gradle
        run: ./gradlew assembleDebug

      - name: Run tests
        run: ./gradlew testDebugUnitTest

      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: wikireader-debug
          path: ./app/build/outputs/apk/debug/app-debug.apk
